# Generated by Django 4.2.16 on 2025-01-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('pending_publish', 'Pending Publish'), ('published', 'Published'), ('pending_delete', 'Pending Delete')], default='pending_publish', max_length=20),
        ),
    ]
