name: Move Issues to Backlog

on:
  issues:
    types: [opened]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      # Step 2: Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Step 3: Move Issue to Backlog
      - name: Move issue to Backlog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh project item-add --field "Column" --value "Backlog" --issue "${{ github.event.issue.node_id }}" --project "https://github.com/users/behemot-biz/projects/5"
