name: Move Issues to Backlog

on:
  issues:
    types: [opened]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      # Step 2: Authenticate and Move Issue to Backlog
      - name: Move issue to Backlog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh project item-add https://github.com/users/behemot-biz/projects/5 --field "Status"="Backlog" --issue "${{ github.event.issue.node_id }}"
